name: ongkir_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_search: ^0.6.3
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  uses-material-design: true
